### ISSUE TITLE
Errors in CI on Build

### ISSUE THREAD

**Issue by rnag** [conda-forge/dataclass-wizard-feedstock#16]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

I haven't had time to look into this, but [builds have been failing](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1082234&view=results) recently.

It seem to fail on `Run docker build` with the following error:

```

  File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 404, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/dataclass-wizard_1731773831970/work/conda_build.sh']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(execute())
             ^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 589, in execute
    api.build(
  File "/opt/conda/lib/python3.12/site-packages/conda_build/api.py", line 209, in build
    return build_tree(
           ^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3655, in build_tree
    packages_from_this = build(
                         ^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2563, in build
    raise BuildScriptException(str(exc), caused_by=exc) from exc
conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/dataclass-wizard_1731773831970/work/conda_build.sh']' returned non-zero exit status 2.

##[error]Bash exited with code '1'.
```

Any help or assistance would be appreciated. I've checked my meta/recipe.yml and it seems OK, not any major changes recently.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by rnag** [comment]
This is done.

I need to get better at Anaconda. Upskill when time allows! 😅
